last_save_width = 4000
last_save_height = 4000
ratio_label = "1:1"
colormap = "turbo"
window_width = 1024
window_height = 768
save_dir = "./viewer_output/"
video_steps = 3200
video_fps = 30
video_width = 1080
video_height = 1920
video_keyframe_stride = 5
time_frames = 900
video_invert_coords = false
video_invert_range = false
